## Exercici 1
**Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.**

In [1]:
import numpy as np
import random
array = np.random.randint(0,500,1000)
print(array)

[ 70 346 471 219 474 220 331 427 304  39   9 188 499 146 353 192 250 301
 182 227 486 136  18 298 340 422  62 442 129  50 209 144  26  93 333 294
  15 107 101 300 147 438 409 208 146 226 243   0 404 122 276 347 204 134
 349   5 120 250 338 119 147 482  39   5 335 261 296   9 474 228 339 299
 125 311 405 449  82 365 363 395 432 449 121 372 119 372 134   6 324 417
 403 479 321 379 305  68 489  42 196 437  62  32 310 321  37 462 423 404
 481 291 205  21 249  26 342  70 113 454 440 138 461  41 316  83  51 129
 440 292 111 216 374  69 258 453 255 228 459  91 266  34 277 379 187 133
 191 216 215 200 345 400 115  38 253  88 334  73  19 401 246 434  42 200
 195  89 149  95  21  85 302 321 402 360 182 116 456 247 461 201 327 197
 259 172 124 359 448 281 220 352  76  52 499 383 189 315 102 152  55  64
  70 101 254 328 402 173 150  55  18 211 171 261 499 263 494 136  73 442
 480 356 348 224  66  94 215 352 394 417 488  69 230 235  54  52 289 184
  46  48 277 162 471 418 400  22 390 130  35  97  9

In [2]:
# promedio
promig = np.mean(array)
# mediana
mitjana = np.median(array)
# desviación
desviació = np.std(array)
# variancia
variança = np.var(array)
# calcular les dimensions d'un array, en aquest cas només hi ha un
longitud = np.shape(array)
#  ens diu cuantes dimensions té el nostre array
dimension = array.ndim

if dimension == 1:
    print(f"Tenim un array de {dimension} dimensió amb una longitud de {longitud}, un valor promig de {promig} i una desviació típica de {desviació}. ")
if  dimension  >= 2:
    print(f"Tenim un array de més d'una dimensió, en total {dimension}, per tant és ERRONI. Podem dir que té una longitud de {longitud}, un valor promig de {promig} i una desviació típica de {desviació}." )

249.859


In [13]:
# de dos dimensions
array2 = np.random.randint(1,30,(3,3))
print(array2)
longitud2 = np.shape(array2)
desviació2 = np.std(array2)
promig2 = np.mean(array2)
dimension2 = array2.ndim
if dimension2 == 1:
    print(f"Tenim un array de {dimension2} dimensió amb una longitud de {longitud2}, un valor promig de {promig2} i una desviació típica de {desviació2}.")
if  dimension2  >= 2:
    print(f"Tenim un array de més d'una dimensió, en total {dimension2}, per tant és ERRONI. Podem dir que té una longitud de {longitud2}, un valor promig de {promig2} i una desviació típica de {desviació2}." )

Tenim un array de més d'una dimensió, en total 2, amb una longitd de (3, 3), un valor promig de 14.666666666666666 i una desviació típica de 5.333333333333333.


## Exercici 2
**Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100**

In [15]:
n = int ( input ( "Introdueix un número qualsevol, que servirà per donar longitud a la matriu quadrada:  " ))
matriu = np.random.randint(0,100, size=(n,n))
print(matriu)

[[32 37 49 23]
 [78 68 65 26]
 [24  8 46 80]
 [17 16 18 40]]


## Exercici 3
**Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.**

In [22]:
n = int ( input ( "Introdueix un número qualsevol, que servirà per donar longitud a la matriu quadrada:  " ))
matriu2 = np.random.randint(0,100, size=(n,n+1))
print(matriu2)
sum_columnes = np.sum(matriu2, axis=0)
sum_files = np.sum(matriu2, axis=1)
print(f"Aquest és el valor del sumatori de les columnes {sum_columnes} i aquest és el valor de la suma de les files {sum_files}")

[[26 35  8]
 [87 89 35]]
Aquest és el valor del sumatori de les columnes [113 124  43] i aquest és el valor de la suma de les files [ 69 211]


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [28]:
m = [2, 3, 4, 4, 5, 6, 6, 7, 7, 8, 10, 10]
f = [1, 3, 2, 4, 4, 4, 6, 4, 6, 7, 9, 10]
np.corrcoef(m, f) 

array([[1.        , 0.93550714],
       [0.93550714, 1.        ]])

In [29]:
# per poder extreure el coeficient de correlació tenim que dividir la covariança ( (array-promig)*(array-promig)/quantitat de valors-1) dividit per (desviació tipica de m*f). 
promig_m = np.mean(m)
promig_f = np.mean(f)

covariança_m = m-promig_m*np.array([1]*len(m))
covariança_f = f-promig_f*np.array([1]*len(f))


numerador = np.dot(covariança_m, covariança_f)


desviacion_m = np.linalg.norm(covariança_m)
desviacion_f = np.linalg.norm(covariança_f)

denominador = desviacion_m*desviacion_f


coeficiente_correlacion = numerador/denominador
print(coeficiente_correlacion)


0.9355071411331456


In [32]:
# Entre 0 y 0,10: correlación inexistente / Entre 0,10 y 0,29: correlación débil / Entre 0,30 y 0,50: correlación moderada / Entre 0,50 y 1,00: correlación fuerte si els valors son negatius en estan indicant que és una correlació inversa
coeficiente_correlacion1 = -0.13
if coeficiente_correlacion > 0 and coeficiente_correlacion <= 0.10:
     print("Correlació inexistent")
if coeficiente_correlacion > 0.10 and coeficiente_correlacion <= 0.29:
     print("correlació débil")
if coeficiente_correlacion > 0.30 and coeficiente_correlacion <= 0.50:
     print("correlació moderada")
if coeficiente_correlacion > 0.50 and coeficiente_correlacion <= 1:
     print("correlació fuerte")

correlació fuerte


In [ ]:
# la fòrmula d'abans l'he tret i adapatada al meu exercici, el meu intent ha sigut aquest i que ha resultat desastrós

m = [2, 3, 4, 4, 5, 6, 6, 7, 7, 8, 10, 10]
f = [1, 3, 2, 4, 4, 4, 6, 4, 6, 7, 9, 10]
np.corrcoef(m, f) 

promig_m = np.mean(m)
print(promig_m)
promig_f = np.mean(f)
print(promig_f)

cantidad_m = len(m)-1
print(cantidad_m)
cantidad_f = len(f)-1

covariancia_m = m-promig_m/cantidad_m 
print(covariancia_m)

covariancia_f = f-promig_f/cantidad_f
print(covariancia_f)

# aqui els resultats de la covariancia ja no son els que hauria :S