## Exercici 1
**Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.**

In [10]:
import numpy as np
import random
array = np.random.randint(0,500,1000)
print(array)

[ 62 133 235 147 141 179 252 434 365 121 260 493  26  93  49  85 146 482
 475 233 190 362 208  18 340 338 197 434 484 311 411  15 332 256 176 442
 144  50  20 434 211 295 261 380 176  83 274 344 499 368 210  27  49 339
   5 208 441 444 348 364 380 271 193 128 299  61 392 329   0 310 172 422
 437 372  20 317 318 422   4 355 483 361 331 224 242 154 496 294   2 453
  92 127 213 477 446  69 113 164 305 365 224 428 443 428 153  78 351  10
 416  94 162 450 191 260 234 414 349 226 430  38 341 311 316 395  14 255
  10  39 297  25 338 201 250 159 124  58 305  46  11 252 243  74 138  22
   6 268   1 164 314 333 344  72  68 311 275 148 282 443 388 283 444 271
 449 284 119 295 390 371 140  31  78 396  94 328 123 397 277 390 345 495
 307 208 278 130 382 162 361 183 179 132 481 318  37 389 337 390 205 302
 436 386 172 421 196 229  87 258 435 304 197 369 328 189  38 426  12 222
   1 406 487 202  23 124 192  95 366 206 130 359 241 156 333 421 135  32
 111 248 393 147 252 376 402 326 229 157 158  48 40

In [29]:
# promedio
promig = np.mean(array)
print(promig)

254.032


In [30]:
# mediana
mitjana = np.median(array)
print(mitjana)

259.0


In [31]:
# desviación
desviació = np.std(array)
print(desviació)

143.0214004126655


In [32]:
# variancia
variança = np.var(array)
print(variança)

20455.120976


In [15]:
# perceptil 50
np.percentile(array, 50)

259.0

In [37]:
# calcular les dimensions d'un array, en aquest cas només hi ha un
longitud = np.shape(array)
print(longitud)

(1000,)


In [26]:
#  ens diu cuantes dimensions té el nostre array
dimension = array.ndim
print(dimension)

1


In [33]:
if  dimension  >= 1:
    print( "Error, té més d'una dimensió" )

Error, té més d'una dimensió


In [39]:
if dimension == 1:
    print(f"Tenim un array de {dimension} dimensió amb una longitud de {longitud}, un valor promig de {promig} i una desviació típica de {desviació}. ")

Tenim un array de 1 dimensió amb una longitud de (1000,), un valor promig de 254.032 i una desviació típica de 143.0214004126655. 


In [42]:
if  dimension  >= 2:
    print(f"Tenim un array de més d'una dimensió, en total {dimension}, amb una longitd de {longitud}, un valor promig de {promig} i una desviació típica de {desviació}." )

In [45]:
array2 = np.random.randint(1,30,(3,3))
print(array2)

[[ 4 26 24]
 [ 4 23  8]
 [ 2 25 10]]


In [49]:
longitud2 = np.shape(array2)
desviació2 = np.std(array2)
promig2 = np.mean(array2)
dimension2 = array2.ndim
if dimension2 == 1:
    print(f"Tenim un array de {dimension2} dimensió amb una longitud de {longitud2}, un valor promig de {promig2} i una desviació típica de {desviació2}.")
if  dimension2  >= 2:
    print(f"Tenim un array de més d'una dimensió, en total {dimension2}, amb una longitd de {longitud2}, un valor promig de {promig2} i una desviació típica de {desviació2}." )

Tenim un array de més d'una dimensió, en total 2, amb una longitd de (3, 3), un valor promig de 14.0 i una desviació típica de 9.672412085697939.


## Exercici 2
**Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100**

In [54]:
matriu = np.random.randint(0,100, size=(5,5))
print(matriu)

[[11 55 61 32 87]
 [64 22 20 93 18]
 [75 40 70 54  4]
 [16 71 11 21 15]
 [44 23 22 13 45]]


In [ ]:
n = int ( input ( "Introdueix un número qualsevol, que servirà per donar longitud a la matriu quadrada:  " ))

In [ ]:
matriu = np.random.randint(0,100, size=(n,n))
print(matriu)

## Exercici 3
**Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.**

In [ ]:
matriu2 = np.random.randint(0,100, size=(4,5))
print(matriu2)

In [ ]:
# suma per columnes
np.sum(values, axis=0)

In [ ]:
# suma per files
np.sum(values, axis=1)

## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [ ]:
matriu2 = np.random.randint(0,100, size=(4,5))
print(mat)
corr_mat = datos.corr(method='pearson')
print(corr_mat)